report:
  config:
    id: 01
    name: Sello FECYT 2025 JSON
    description: Esta configuración expone los datos para la optención del sello fecyt en formato Json
    authorization: admin
    format: json
  data:

    - id: 2
      description: Composición y apertura del equipo editorial (ver 3.1)
      operation: about
      params: editorialTeam
      output:
        fields:

    - id: 3
      description: Información pública acerca del envío de los manuscritos (ver 3.2)
      operation: about
      params: submissions
      output:
        fields:

    - id: 4
      description: Periodicidad (ver 3.3)
      operation: about
      params: 
      output:
        fields: 

    - id: 5
      description: Arbitraje científico externo (ver 3.4)
      operation: reviewers
      params: 
      output:
        fields: givenName,familyName